name: Save Kingdoms Players Data

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install requests

      - name: Run Python with env
        run: python -m src.main 1001 3850
        env:
          ROK_B_TOKEN: ${{ secrets.ROK_B_TOKEN}}
          ROK_P_TOKEN: ${{ secrets.ROK_P_TOKEN}}
          MODE: save_data
          
      - name: Commit result file
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add data/kingdoms/

          # 如果没有变化，避免报错
          git diff --cached --quiet || git commit -m "Update kingdoms player data"

          git push
